"""
src/core/services/key_extraction_service.py
============================================
Extracts AR document reference keys from raw text.

Pipeline (two stages):
  Stage 1 — Positional tabular extraction (deterministic)
             Detects label-row / value-row table blocks as generated by
             reportlab and other PDF tools where pypdf splits them into
             separate lines.  Also runs anchor regex for inline labels.

  Stage 2 — LLM validation + supplement
             Receives stage-1 results AND the raw text.
             Validates each found key, corrects obvious errors,
             and adds any keys the regex missed.

Keys extracted:
  po_number, inv_number, grn_number,
  contract_number, payment_ref, credit_note_number
"""
from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Normalization
# ─────────────────────────────────────────────────────────────────────────────

def normalize_ref(value: str) -> str:
    """Strip non-alphanumeric and uppercase — deterministic linking key."""
    return re.sub(r"[^A-Z0-9]", "", value.upper())


# ─────────────────────────────────────────────────────────────────────────────
# Stage 1A — Positional tabular extraction
# Handles PDFs where label row and value row are on separate lines:
#   "PO No\nInvoice No\nPO-001\nINV-001"
# ─────────────────────────────────────────────────────────────────────────────

# All label variants that appear in our generated PDFs
_LABEL_MAP: dict[str, Optional[str]] = {
    "po no":              "po_number",
    "purchase order no":  "po_number",
    "invoice no":         "inv_number",
    "tax invoice no":     "inv_number",
    "bill no":            "inv_number",
    "ref invoice no":     "inv_number",
    "grn no":             "grn_number",
    "grn number":         "grn_number",
    "delivery note no":   "grn_number",
    "receipt no":         "grn_number",
    "contract no":        "contract_number",
    "rate contract no":   "contract_number",
    "agreement no":       "contract_number",
    "payment ref":        "payment_ref",
    "utr":                "payment_ref",
    "neft ref":           "payment_ref",
    "rtgs ref":           "payment_ref",
    "credit note no":     "credit_note_number",
    "cn no":              "credit_note_number",
    "debit note no":      "credit_note_number",
    # These appear as labels but values are dates/text — map to None to skip
    "po date":            None,
    "invoice date":       None,
    "due date":           None,
    "grn date":           None,
    "payment date":       None,
    "date":               None,
    "valid until":        None,
}

_DATE_RE = re.compile(r"^\d{1,2}[-/]\w{2,}[-/]\d{2,4}$")
_REF_RE  = re.compile(r"^[A-Z]{1,}[A-Z0-9/\-]*\d+", re.IGNORECASE)
_SKIP    = {"accepted","pending","cleared","partial","full","advance","n/a",
            "conditional acceptance","status","description"}


def _norm_label(s: str) -> str:
    return re.sub(r"[\s:\.]+$", "", s).strip().lower()


def _is_ref_value(s: str) -> bool:
    s = s.strip()
    if _DATE_RE.match(s):           return False
    if s.lower() in _SKIP:          return False
    if len(s) < 3:                  return False
    return bool(_REF_RE.match(s))


def _extract_tabular(text: str) -> dict[str, str]:
    """
    Scan for runs of known label lines, then map each label's
    positional offset to the corresponding value line below.
    """
    lines  = [l.strip() for l in text.split("\n") if l.strip()]
    n      = len(lines)
    result: dict[str, str] = {}
    i = 0

    while i < n:
        ln = _norm_label(lines[i])
        if ln not in _LABEL_MAP:
            i += 1
            continue

        # Collect the full label block starting at i
        labels: list[tuple[Optional[str], int]] = []  # (key_type, offset)
        j = i
        while j < n and _norm_label(lines[j]) in _LABEL_MAP:
            key_type = _LABEL_MAP[_norm_label(lines[j])]
            labels.append((key_type, j - i))
            j += 1

        values_start = j  # values immediately follow labels

        for key_type, offset in labels:
            if key_type is None:
                continue
            val_idx = values_start + offset
            if val_idx < n:
                val = lines[val_idx].strip()
                if _is_ref_value(val) and key_type not in result:
                    result[key_type] = val

        i = values_start + len(labels)

    return result


# ─────────────────────────────────────────────────────────────────────────────
# Stage 1B — Anchor regex (inline "PO No: PO-001" patterns)
# ─────────────────────────────────────────────────────────────────────────────

# ─────────────────────────────────────────────────────────────────────────────
# Stage 1B — Anchor regex (inline "PO No: PO-001" patterns)
# ─────────────────────────────────────────────────────────────────────────────

_SEP = r"[\s:\.]+"
# Reference values MUST contain at least one digit — this prevents pure
# uppercase words like "GRN", "INVOICE", "Valid" from matching as values.
_VAL = r"([A-Z0-9][A-Z0-9/\-]{1,38}[A-Z0-9](?=\D|$)|[A-Z]*\d[A-Z0-9/\-]*)"

_ANCHORS: dict[str, list[str]] = {
    "po_number": [
        rf"P\.?O\.?{_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
        rf"Purchase\s+Order{_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
        rf"Order{_SEP}(?:Number|No\.?|Reference|#){_SEP}{_VAL}",
    ],
    "inv_number": [
        rf"(?:Tax\s+)?Invoice{_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
        rf"Bill{_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
    ],
    "grn_number": [
        # Label is required (non-optional) to avoid GRN word matching itself
        rf"\bGRN{_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
        rf"Goods\s+Receipt{_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
        rf"Delivery\s+(?:Note|Challan){_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
        # Bare "GRN:" followed directly by the value (no sublabel)
        rf"\bGRN\s*:\s*{_VAL}",
    ],
    "contract_number": [
        rf"(?:Rate\s+)?Contract{_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
        rf"Agreement{_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
    ],
    "payment_ref": [
        rf"\bUTR{_SEP}(?:Number|No\.?|#)?{_SEP}([A-Z0-9]{{8,30}})",
        rf"(?:NEFT|RTGS|IMPS){_SEP}(?:Ref\.?|Reference|#){_SEP}([A-Z0-9]{{8,30}})",
        rf"Payment{_SEP}Ref(?:erence)?{_SEP}(?:Number|No\.?|#)?{_SEP}([A-Z0-9]{{8,30}})",
        rf"Cheque{_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
    ],
    "credit_note_number": [
        rf"Credit\s+Note{_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
        rf"\bCN{_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
        rf"Debit\s+Note{_SEP}(?:Number|No\.?|#){_SEP}{_VAL}",
    ],
}

_MIN_NORM = 3


def _extract_anchors(text: str) -> dict[str, str]:
    results: dict[str, str] = {}
    for key_type, patterns in _ANCHORS.items():
        for pattern in patterns:
            m = re.search(pattern, text, re.IGNORECASE)
            if m:
                raw  = m.group(1).strip().rstrip(".:,")
                norm = normalize_ref(raw)
                if len(norm) >= _MIN_NORM and _is_ref_value(raw):
                    results[key_type] = raw
                    break
    return results


# ─────────────────────────────────────────────────────────────────────────────
# Stage 2 — LLM validates stage-1 results and adds missed keys
# ─────────────────────────────────────────────────────────────────────────────

_LLM_PROMPT = """You are an AR document parser. Validate and complete the extracted reference keys.

DOCUMENT TYPE: {doc_type}

DOCUMENT TEXT (first 3000 chars):
{text}

STAGE-1 EXTRACTION RESULTS (from regex — may contain errors):
{stage1_json}

TASK:
1. For each key in stage-1: verify the value is correct. If wrong or missing, find the right value in the document text.
2. Find any reference keys that stage-1 missed entirely.

RULES:
- Only return keys that are EXPLICITLY present in the document text.
- Do NOT invent values. Do NOT guess.
- Reference values look like: PO-BK-2025-001, INV-2025-004, GRN-KCE-2025-LAB-001, PAY-2025-001A, CN-KCE-2025-001
- Dates (12-Jan-2025), plain words (Valid, Accepted) are NOT reference values.
- If a key is truly absent from this document, return null for it.

Return ONLY valid JSON with exactly these keys (null if absent):
{{
  "po_number":          "...",
  "inv_number":         "...",
  "grn_number":         "...",
  "contract_number":    "...",
  "payment_ref":        "...",
  "credit_note_number": "..."
}}"""


async def _validate_via_llm(
    text: str,
    doc_type: str,
    stage1: dict[str, str],
) -> dict[str, str]:
    """LLM validates stage-1 and fills gaps. Returns merged results."""
    try:
        from src.handlers.http_clients.llm_client import get_llm_client
        client = get_llm_client()

        prompt = _LLM_PROMPT.format(
            doc_type    = doc_type,
            text        = text[:3000],
            stage1_json = json.dumps(stage1, indent=2),
        )
        raw = await client.chat_fast(
            prompt = prompt,
            system = "You are a precise AR document parser. Return only valid JSON. No markdown.",
            json_mode = True,
        )
        parsed = json.loads(raw) if isinstance(raw, str) else raw
        results: dict[str, str] = {}
        for key_type in ("po_number","inv_number","grn_number",
                         "contract_number","payment_ref","credit_note_number"):
            val = parsed.get(key_type)
            if val and isinstance(val, str):
                raw_val = val.strip().rstrip(".:,")
                if len(normalize_ref(raw_val)) >= _MIN_NORM and _is_ref_value(raw_val):
                    results[key_type] = raw_val
        return results
    except Exception as e:
        logger.warning(f"LLM key validation failed (non-fatal): {e}")
        return stage1  # fall back to stage-1 results


# ─────────────────────────────────────────────────────────────────────────────
# ExtractedKey dataclass
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class ExtractedKey:
    key_type:       str
    key_value_raw:  str
    key_value_norm: str
    confidence:     float
    source:         str  # "tabular" | "regex" | "llm" | "manual"


# ─────────────────────────────────────────────────────────────────────────────
# Public entry point
# ─────────────────────────────────────────────────────────────────────────────

async def extract_document_keys(text: str, doc_type: str) -> list[ExtractedKey]:
    """
    Two-stage extraction:
      1. Tabular positional + anchor regex (deterministic)
      2. LLM validates + supplements stage-1

    Returns list of ExtractedKey ready for DB insertion.
    """
    if not text or not text.strip():
        return []

    # Stage 1
    tabular = _extract_tabular(text)
    anchors = _extract_anchors(text)

    # Merge — tabular wins over anchors for same key (more reliable for our PDFs)
    stage1: dict[str, str] = {**anchors, **tabular}
    logger.info(
        f"Key extraction stage1: tabular={list(tabular.keys())} "
        f"regex={list(anchors.keys())} for doc_type={doc_type}"
    )

    # Stage 2 — LLM validates and fills
    final = await _validate_via_llm(text, doc_type, stage1)
    logger.info(f"Key extraction final: {list(final.keys())} for doc_type={doc_type}")

    keys: list[ExtractedKey] = []
    for key_type, raw_val in final.items():
        # Determine source
        if key_type in tabular and tabular[key_type] == raw_val:
            source     = "regex"   # "tabular" shown as regex to FA — both deterministic
            confidence = 0.97
        elif key_type in anchors and anchors[key_type] == raw_val:
            source     = "regex"
            confidence = 0.93
        else:
            source     = "llm"
            confidence = 0.80

        keys.append(ExtractedKey(
            key_type       = key_type,
            key_value_raw  = raw_val,
            key_value_norm = normalize_ref(raw_val),
            confidence     = confidence,
            source         = source,
        ))

    return keys
